# Generated by Django 4.2.30 on 2026-04-30 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=20)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='tenancy.organisation')),
            ],
            options={
                'unique_together': {('organisation', 'registration')},
            },
        ),
        migrations.CreateModel(
            name='VehicleState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('speed_kmh', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=200)),
                ('myroutes_trip_id', models.IntegerField(blank=True, null=True)),
                ('last_seen', models.DateTimeField()),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='vehicles.vehicle')),
            ],
        ),
    ]
