# Generated by Django 4.2.30 on 2026-06-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_vehicle_emissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel_source_pref',
            field=models.CharField(choices=[('auto', 'Auto (best available)'), ('can', 'CAN bus'), ('obd', 'OBD-II'), ('probe', 'Analog/LLS probe')], default='auto', help_text='Pin the fuel data source, or Auto to pick the best available per ping', max_length=5),
        ),
    ]
