# Generated by Django 4.2.30 on 2026-04-30 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('speed_kmh', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=200)),
                ('myroutes_trip_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pings', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['vehicle', 'received_at'], name='tracking_gp_vehicle_ba9a9e_idx')],
            },
        ),
    ]
