# Generated by Django 4.2.30 on 2026-04-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsping',
            name='device_timestamp',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='gpsping',
            index=models.Index(fields=['vehicle', 'device_timestamp'], name='tracking_gp_vehicle_f5efc7_idx'),
        ),
    ]
