# Generated by Django 4.2.30 on 2026-04-30 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        ('tracking', '0002_gpsping_device_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(blank=True, max_length=200)),
                ('myroutes_trip_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('start_lat', models.FloatField()),
                ('start_lon', models.FloatField()),
                ('end_lat', models.FloatField(blank=True, null=True)),
                ('end_lon', models.FloatField(blank=True, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('max_speed_kmh', models.FloatField(blank=True, null=True)),
                ('ping_count', models.PositiveIntegerField(default=0)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_trips', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='gpsping',
            name='tracked_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pings', to='tracking.trackedtrip'),
        ),
        migrations.AddIndex(
            model_name='trackedtrip',
            index=models.Index(fields=['vehicle', 'started_at'], name='tracking_tr_vehicle_9e8712_idx'),
        ),
    ]
