# Generated by Django 4.2.30 on 2026-04-30 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_home_depot_vehicledepotassignment'),
        ('tracking', '0003_trackedtrip_gpsping_tracked_trip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('speeding', 'Speeding'), ('idle', 'Idle')], db_index=True, max_length=10)),
                ('value', models.FloatField(help_text='Observed value (km/h or minutes idle)')),
                ('threshold', models.FloatField(help_text='Threshold that was breached')),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=200)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['vehicle', 'occurred_at'], name='tracking_al_vehicle_4d20b7_idx'), models.Index(fields=['kind', 'resolved_at'], name='tracking_al_kind_335959_idx')],
            },
        ),
    ]
