# Generated by Django 4.2.30 on 2026-05-03 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0003_vehicle_fuel_tank_capacity'),
        ('tracking', '0004_alert_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='kind',
            field=models.CharField(choices=[('speeding', 'Speeding'), ('idle', 'Idle'), ('fuel_theft', 'Fuel Theft')], db_index=True, max_length=10),
        ),
        migrations.CreateModel(
            name='DeliveryShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('note', models.CharField(blank=True, help_text="e.g. 'Order #1234 delivery'", max_length=500)),
                ('destination_lat', models.FloatField(blank=True, null=True)),
                ('destination_lon', models.FloatField(blank=True, null=True)),
                ('destination_address', models.CharField(blank=True, help_text='Human-readable destination shown on tracking page.', max_length=300)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Set when dispatcher marks delivery as complete.', null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_shares', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_shares', to='vehicles.vehicle')),
            ],
        ),
    ]
