# Generated by Django 4.2.30 on 2026-05-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_deliveryshare_and_destinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryshare',
            name='stop_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text="This customer's position in the delivery run (e.g. 3).", null=True),
        ),
        migrations.AddField(
            model_name='deliveryshare',
            name='total_stops',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Total stops in the run (e.g. 5).', null=True),
        ),
    ]
