# Generated by Django 4.2.30 on 2026-05-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_alert_kind_extend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='kind',
            field=models.CharField(choices=[('speeding', 'Speeding'), ('idle', 'Idle'), ('fuel_theft', 'Fuel Theft'), ('fuel_drain', 'Fuel Drain'), ('probe_fault', 'Probe Fault'), ('excess_consumption', 'Excess Consumption'), ('harsh_braking', 'Harsh Braking'), ('harsh_accel', 'Harsh Acceleration'), ('lane_departure', 'Lane Departure'), ('fatigue', 'Driver Fatigue'), ('phone_use', 'Phone Use'), ('seatbelt', 'Seatbelt Violation'), ('camera_event', 'Camera Event')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['vehicle', 'kind', 'occurred_at'], name='tracking_al_vehicle_8598a4_idx'),
        ),
    ]
