# Generated by Django 5.1.15 on 2026-05-12 18:39

from django.db import migrations, models


def create_road_segment_table(apps, schema_editor):
    """PostGIS table for OSM ways (populated offline via osm2pgsql — see scripts/road_osm/)."""
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as c:
        c.execute("CREATE EXTENSION IF NOT EXISTS postgis")
        c.execute(
            """
            CREATE TABLE IF NOT EXISTS tracking_roadsegment (
                osm_way_id bigint PRIMARY KEY,
                highway varchar(64) NOT NULL,
                maxspeed text,
                geom geometry(LineString, 4326) NOT NULL
            )
            """
        )
        c.execute(
            "CREATE INDEX IF NOT EXISTS tracking_roadsegment_geom_gix "
            "ON tracking_roadsegment USING GIST (geom)"
        )


def drop_road_segment_table(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as c:
        c.execute("DROP TABLE IF EXISTS tracking_roadsegment CASCADE")


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_alter_alert_kind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadSpeedCache',
            fields=[
                ('cell_key', models.CharField(help_text='Quantized lat|lon cell key.', max_length=40, primary_key=True, serialize=False)),
                ('limit_kmh', models.FloatField()),
                ('osm_way_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tracking_roadspeedcache',
            },
        ),
        migrations.AddField(
            model_name='gpsping',
            name='road_speed_limit_kmh',
            field=models.FloatField(blank=True, help_text='Posted or fallback speed limit (km/h) used for this ping when road limits are enabled.', null=True),
        ),
        migrations.AddField(
            model_name='gpsping',
            name='road_speed_source',
            field=models.CharField(blank=True, help_text='traccar, cache, postgis, or fallback', max_length=16),
        ),
        migrations.RunPython(create_road_segment_table, drop_road_segment_table),
    ]
