# Generated by Django 5.1.15 on 2026-05-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_syncoutbox'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='syncoutbox',
            new_name='tracking_sy_destina_78d5f8_idx',
            old_name='tracking_syncoutbox_dest_idx',
        ),
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], db_index=True, default='warning', max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='kind',
            field=models.CharField(choices=[('speeding', 'Speeding'), ('idle', 'Idle'), ('fuel_theft', 'Fuel Theft'), ('fuel_drain', 'Fuel Drain'), ('probe_fault', 'Probe Fault'), ('excess_consumption', 'Excess Consumption'), ('harsh_braking', 'Harsh Braking'), ('harsh_accel', 'Harsh Acceleration'), ('harsh_cornering', 'Harsh Cornering'), ('lane_departure', 'Lane Departure'), ('fatigue', 'Driver Fatigue'), ('phone_use', 'Phone Use'), ('seatbelt', 'Seatbelt Violation'), ('camera_event', 'Camera Event'), ('geofence_after_hours', 'Geofence After-Hours')], db_index=True, max_length=20),
        ),
    ]
