# Generated by Django 4.2.30 on 2026-04-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geofence',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='geofence',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='geofence',
            name='radius_m',
        ),
        migrations.AddField(
            model_name='geofence',
            name='polygon',
            field=models.JSONField(default=list, help_text='List of [lon, lat] coordinate pairs forming a closed polygon.'),
        ),
    ]
