# Generated by Django 4.2.30 on 2026-05-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofences', '0002_remove_geofence_lat_remove_geofence_lon_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='geofenceevent',
            index=models.Index(fields=['vehicle', 'kind', 'occurred_at'], name='geofences_g_vehicle_584675_idx'),
        ),
    ]
