# Generated by Django 4.2.30 on 2026-05-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fuelevent',
            new_name='fuel_fuelev_vehicle_5155dd_idx',
            old_name='fuel_event_vehicle_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='fuelreading',
            new_name='fuel_fuelre_vehicle_045b4d_idx',
            old_name='fuel_reading_vehicle_ts_idx',
        ),
        migrations.AlterField(
            model_name='fuelevent',
            name='delta_litres',
            field=models.FloatField(help_text='Change in litres (+refuel, −drain/theft)'),
        ),
        migrations.AlterField(
            model_name='fuelevent',
            name='level_after',
            field=models.FloatField(help_text='Fuel level (L) after event'),
        ),
        migrations.AlterField(
            model_name='fuelevent',
            name='level_before',
            field=models.FloatField(help_text='Fuel level (L) before event'),
        ),
    ]
