# Generated by Django 4.2.30 on 2026-05-08 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_vehicle_expected_fuel_lper100km'),
        ('fuel', '0002_rename_fuel_event_vehicle_ts_idx_fuel_fuelev_vehicle_5155dd_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelreading',
            name='raw_sensor_value',
            field=models.FloatField(blank=True, help_text='Pre-calibration sensor output — preserved for diagnostics', null=True),
        ),
        migrations.AlterField(
            model_name='fuelevent',
            name='kind',
            field=models.CharField(choices=[('refuel', 'Refuel'), ('theft', 'Fuel Theft'), ('drain', 'Unexplained Drain'), ('probe', 'Probe Fault'), ('excess', 'Excess Consumption')], db_index=True, max_length=10),
        ),
        migrations.CreateModel(
            name='TankCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottom_blind_litres', models.FloatField(default=0.0, help_text='Volume (L) in the unreadable dead-zone at the bottom of the tank')),
                ('top_blind_litres', models.FloatField(default=0.0, help_text='Expansion space (L) at the top of the tank the probe cannot reach')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tank_calibration', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_value', models.FloatField(help_text='Sensor output at this calibration step')),
                ('litres', models.FloatField(help_text='Actual measured volume (L) at this step')),
                ('calibration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='fuel.tankcalibration')),
            ],
            options={
                'ordering': ['raw_value'],
                'unique_together': {('calibration', 'raw_value')},
            },
        ),
    ]
