# Generated by Django 4.2.30 on 2026-06-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0005_tankcalibration_polynomial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelreading',
            name='fuel_level_pct',
            field=models.FloatField(blank=True, help_text='Raw OEM/OBD fuel level percentage — preserved for audit + UI', null=True),
        ),
        migrations.AddField(
            model_name='fuelreading',
            name='fuel_rate_lph',
            field=models.FloatField(blank=True, help_text='Instantaneous burn rate (L/h) when the ECU provides it', null=True),
        ),
        migrations.AddField(
            model_name='fuelreading',
            name='source',
            field=models.CharField(choices=[('can', 'CAN bus (ECU)'), ('obd', 'OBD-II'), ('probe', 'Analog/LLS probe'), ('est', 'Estimated (% × capacity)')], db_index=True, default='probe', help_text='Where this reading came from — CAN/OBD vehicles bypass the strapping table', max_length=5),
        ),
        migrations.AddField(
            model_name='fuelreading',
            name='total_fuel_used_litres',
            field=models.FloatField(blank=True, help_text='Monotonic ECU counter snapshot of litres burned since reset', null=True),
        ),
    ]
