# Generated by Django 4.2.30 on 2026-04-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('id_number', models.CharField(blank=True, help_text='SA ID number', max_length=13)),
                ('phone_e164', models.CharField(blank=True, help_text='E.164 e.g. +27821234567', max_length=16)),
                ('licence_code', models.CharField(blank=True, choices=[('C8', 'Code 8 (Motor vehicle)'), ('C10', 'Code 10 (Heavy motor vehicle)'), ('C14', 'Code 14 (Extra-heavy)'), ('EB', 'Code EB (Motor vehicle with trailer)')], max_length=4)),
                ('licence_expiry', models.DateField(blank=True, null=True)),
                ('pdp_number', models.CharField(blank=True, help_text='Professional Driving Permit number', max_length=30)),
                ('pdp_expiry', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
