# Generated by Django 4.2.30 on 2026-04-30 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scored_date', models.DateField(db_index=True)),
                ('score', models.PositiveSmallIntegerField()),
                ('trips', models.PositiveSmallIntegerField(default=0)),
                ('distance_km', models.FloatField(default=0.0)),
                ('speeding_events', models.PositiveSmallIntegerField(default=0)),
                ('harsh_accel_events', models.PositiveSmallIntegerField(default=0)),
                ('idling_minutes', models.FloatField(default=0.0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='drivers.driver')),
            ],
            options={
                'ordering': ['-scored_date'],
                'unique_together': {('driver', 'scored_date')},
            },
        ),
    ]
