# Generated by Django 4.2.30 on 2026-04-30 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to='tenancy.organisation')),
            ],
            options={
                'unique_together': {('organisation', 'name')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('dispatcher', 'Dispatcher'), ('viewer', 'Viewer')], default='dispatcher', max_length=20),
        ),
        migrations.CreateModel(
            name='UserDepotAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='tenancy.depot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depot_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'depot')},
            },
        ),
    ]
