# Generated by Django 4.2.30 on 2026-04-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_depot_user_role_userdepotaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='speed_limit_kmh',
            field=models.PositiveSmallIntegerField(default=120, help_text='Fleet-wide speeding threshold in km/h.'),
        ),
    ]
