# Generated by Django 5.1.15 on 2026-05-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0008_promote_username_admin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='road_speed_limits_enabled',
            field=models.BooleanField(default=False, help_text='Use OSM-backed road speeds (plus cache) when data is loaded; otherwise only speed_limit_kmh applies.'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='speeding_grace_kmh',
            field=models.FloatField(default=0.0, help_text='Extra km/h over the limit before a speeding alert is raised.'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='speed_limit_kmh',
            field=models.PositiveSmallIntegerField(default=120, help_text='Fallback fleet speeding threshold (km/h) when road-specific data is unavailable, or when road limits are disabled.'),
        ),
    ]
