# Generated by Django 5.1.15 on 2026-05-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0013_organisation_require_2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='whatsapp_driver_notify_enabled',
            field=models.BooleanField(default=False, help_text='Send WhatsApp messages directly to drivers when alerts are triggered (requires META_WHATSAPP_* env vars).'),
        ),
    ]
