# Generated by Django 4.2.30 on 2026-05-04 11:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracking', '0006_deliveryshare_stop_number'),
        ('tenancy', '0005_seat_limit_consumes_license'),
        ('vehicles', '0005_vehiclestate_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('source', models.CharField(choices=[('traccar', 'Traccar'), ('vendor', 'Vendor'), ('manual_upload', 'Manual upload')], default='vendor', max_length=20)),
                ('external_channel_id', models.CharField(blank=True, max_length=120)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_channels', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['vehicle_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('recorded_start', models.DateTimeField(blank=True, null=True)),
                ('recorded_end', models.DateTimeField(blank=True, null=True)),
                ('trigger_type', models.CharField(choices=[('harsh_event', 'Harsh event'), ('speeding', 'Speeding'), ('manual', 'Manual'), ('scheduled', 'Scheduled'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('ingest_source', models.CharField(choices=[('traccar', 'Traccar'), ('webhook', 'Webhook'), ('direct_upload', 'Direct upload'), ('vendor', 'Vendor')], max_length=20)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('storage_key', models.CharField(blank=True, max_length=512)),
                ('playback_url', models.URLField(blank=True, max_length=2048)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('delete_after', models.DateTimeField(blank=True, null=True)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_assets', to='tracking.alert')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='video_telematics.videochannel')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_assets', to='tenancy.organisation')),
                ('tracked_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_assets', to='tracking.trackedtrip')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_assets', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoUploadIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_key', models.CharField(max_length=512)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('trigger_type', models.CharField(choices=[('harsh_event', 'Harsh event'), ('speeding', 'Speeding'), ('manual', 'Manual'), ('scheduled', 'Scheduled'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_upload_intents', to='tenancy.organisation')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_upload_intents', to='vehicles.vehicle')),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='video_telem_expires_f0323b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='videochannel',
            index=models.Index(fields=['vehicle', 'source'], name='video_telem_vehicle_d705cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='videochannel',
            constraint=models.UniqueConstraint(fields=('vehicle', 'name', 'source'), name='video_channel_unique_vehicle_name_source'),
        ),
        migrations.AddIndex(
            model_name='videoasset',
            index=models.Index(fields=['organisation', '-occurred_at'], name='video_telem_organis_ee5229_idx'),
        ),
        migrations.AddIndex(
            model_name='videoasset',
            index=models.Index(fields=['vehicle', '-occurred_at'], name='video_telem_vehicle_12d4f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='videoasset',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('ingest_source', 'external_id'), name='video_asset_unique_ingest_external_id'),
        ),
    ]
