# Generated by Django 4.2.30 on 2026-05-06 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_telematics', '0002_videotelematics_enhancements'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cliprequest',
            new_name='video_telem_organis_1cebcb_idx',
            old_name='video_telem_clipreq_org_idx',
        ),
        migrations.RenameIndex(
            model_name='cliprequest',
            new_name='video_telem_status_c8bd00_idx',
            old_name='video_telem_clipreq_status_idx',
        ),
    ]
