# Generated by Django 5.1.15 on 2026-05-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_telematics', '0004_videochannel_stream_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoasset',
            name='ingest_source',
            field=models.CharField(choices=[('traccar', 'Traccar'), ('webhook', 'Webhook'), ('direct_upload', 'Direct upload'), ('vendor', 'Vendor'), ('streamax', 'Streamax')], max_length=20),
        ),
    ]
