from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("geofences", "0001_initial"),
        ("tenancy", "0001_initial"),
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomReportDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("domain", models.CharField(choices=[("speed", "Speed"), ("fuel", "Fuel"), ("geofence", "Geofence"), ("route", "Route")], max_length=20)),
                ("columns", models.JSONField(default=list)),
                ("metrics", models.JSONField(default=list)),
                ("group_by", models.JSONField(default=list)),
                ("filters", models.JSONField(default=dict)),
                ("sort_by", models.JSONField(default=list)),
                ("schedule_config", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="custom_report_definitions", to="tenancy.organisation")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="custom_reports", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["name"], "unique_together": {("organisation", "name")}},
        ),
        migrations.CreateModel(
            name="DailyFuelMetrics",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metric_date", models.DateField(db_index=True)),
                ("reading_count", models.PositiveIntegerField(default=0)),
                ("opening_fuel_litres", models.FloatField(default=0.0)),
                ("closing_fuel_litres", models.FloatField(default=0.0)),
                ("fuel_delta_litres", models.FloatField(default=0.0)),
                ("total_refuel_litres", models.FloatField(default=0.0)),
                ("total_drain_litres", models.FloatField(default=0.0)),
                ("theft_event_count", models.PositiveIntegerField(default=0)),
                ("drain_event_count", models.PositiveIntegerField(default=0)),
                ("excess_event_count", models.PositiveIntegerField(default=0)),
                ("probe_fault_event_count", models.PositiveIntegerField(default=0)),
                ("inferred_data", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("depot", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="daily_fuel_metrics", to="tenancy.depot")),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="daily_fuel_metrics", to="tenancy.organisation")),
                ("vehicle", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="daily_fuel_metrics", to="vehicles.vehicle")),
            ],
            options={"ordering": ["-metric_date", "vehicle_id"], "unique_together": {("vehicle", "metric_date")}},
        ),
        migrations.CreateModel(
            name="DailyGeofenceMetrics",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metric_date", models.DateField(db_index=True)),
                ("enter_count", models.PositiveIntegerField(default=0)),
                ("exit_count", models.PositiveIntegerField(default=0)),
                ("visit_count", models.PositiveIntegerField(default=0)),
                ("total_dwell_minutes", models.FloatField(default=0.0)),
                ("avg_dwell_minutes", models.FloatField(default=0.0)),
                ("max_dwell_minutes", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("depot", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="daily_geofence_metrics", to="tenancy.depot")),
                ("geofence", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="daily_metrics", to="geofences.geofence")),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="daily_geofence_metrics", to="tenancy.organisation")),
                ("vehicle", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="daily_geofence_metrics", to="vehicles.vehicle")),
            ],
            options={"ordering": ["-metric_date", "vehicle_id"], "unique_together": {("vehicle", "geofence", "metric_date")}},
        ),
        migrations.CreateModel(
            name="DailyVehicleMetrics",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metric_date", models.DateField(db_index=True)),
                ("trip_count", models.PositiveIntegerField(default=0)),
                ("ping_count", models.PositiveIntegerField(default=0)),
                ("distance_km", models.FloatField(default=0.0)),
                ("avg_speed_kmh", models.FloatField(default=0.0)),
                ("max_speed_kmh", models.FloatField(default=0.0)),
                ("idle_alert_count", models.PositiveIntegerField(default=0)),
                ("speeding_alert_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("depot", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="daily_vehicle_metrics", to="tenancy.depot")),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="daily_vehicle_metrics", to="tenancy.organisation")),
                ("vehicle", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="daily_metrics", to="vehicles.vehicle")),
            ],
            options={"ordering": ["-metric_date", "vehicle_id"], "unique_together": {("vehicle", "metric_date")}},
        ),
        migrations.CreateModel(
            name="CustomReportRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("pending", "Pending"), ("running", "Running"), ("success", "Success"), ("failed", "Failed")], default="pending", max_length=20)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("artifact_path", models.CharField(blank=True, max_length=500)),
                ("format", models.CharField(default="csv", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("definition", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="runs", to="reporting.customreportdefinition")),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="custom_report_runs", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(model_name="dailyvehiclemetrics", index=models.Index(fields=["organisation", "metric_date"], name="reporting_da_org_id_7fb2ea_idx")),
        migrations.AddIndex(model_name="dailyvehiclemetrics", index=models.Index(fields=["vehicle", "metric_date"], name="reporting_da_vehicle_9378e6_idx")),
        migrations.AddIndex(model_name="dailyvehiclemetrics", index=models.Index(fields=["depot", "metric_date"], name="reporting_da_depot_i_2872a8_idx")),
        migrations.AddIndex(model_name="dailyfuelmetrics", index=models.Index(fields=["organisation", "metric_date"], name="reporting_da_org_id_a467f0_idx")),
        migrations.AddIndex(model_name="dailyfuelmetrics", index=models.Index(fields=["vehicle", "metric_date"], name="reporting_da_vehicle_0ac279_idx")),
        migrations.AddIndex(model_name="dailyfuelmetrics", index=models.Index(fields=["depot", "metric_date"], name="reporting_da_depot_i_4e25a2_idx")),
        migrations.AddIndex(model_name="dailygeofencemetrics", index=models.Index(fields=["organisation", "metric_date"], name="reporting_da_org_id_88db86_idx")),
        migrations.AddIndex(model_name="dailygeofencemetrics", index=models.Index(fields=["vehicle", "metric_date"], name="reporting_da_vehicle_2ec5af_idx")),
        migrations.AddIndex(model_name="dailygeofencemetrics", index=models.Index(fields=["depot", "metric_date"], name="reporting_da_depot_i_99f4be_idx")),
        migrations.AddIndex(model_name="dailygeofencemetrics", index=models.Index(fields=["geofence", "metric_date"], name="reporting_da_geofenc_28613f_idx")),
    ]
