# Generated by Django 5.1.15 on 2026-05-15 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailyfuelmetrics',
            new_name='reporting_d_organis_b81597_idx',
            old_name='reporting_da_org_id_a467f0_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyfuelmetrics',
            new_name='reporting_d_vehicle_0075d9_idx',
            old_name='reporting_da_vehicle_0ac279_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyfuelmetrics',
            new_name='reporting_d_depot_i_72c16a_idx',
            old_name='reporting_da_depot_i_4e25a2_idx',
        ),
        migrations.RenameIndex(
            model_name='dailygeofencemetrics',
            new_name='reporting_d_organis_dfb10a_idx',
            old_name='reporting_da_org_id_88db86_idx',
        ),
        migrations.RenameIndex(
            model_name='dailygeofencemetrics',
            new_name='reporting_d_vehicle_a8dcd6_idx',
            old_name='reporting_da_vehicle_2ec5af_idx',
        ),
        migrations.RenameIndex(
            model_name='dailygeofencemetrics',
            new_name='reporting_d_depot_i_1f8ac2_idx',
            old_name='reporting_da_depot_i_99f4be_idx',
        ),
        migrations.RenameIndex(
            model_name='dailygeofencemetrics',
            new_name='reporting_d_geofenc_b6148e_idx',
            old_name='reporting_da_geofenc_28613f_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyvehiclemetrics',
            new_name='reporting_d_organis_ee6e5d_idx',
            old_name='reporting_da_org_id_7fb2ea_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyvehiclemetrics',
            new_name='reporting_d_vehicle_7cebaa_idx',
            old_name='reporting_da_vehicle_9378e6_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyvehiclemetrics',
            new_name='reporting_d_depot_i_48ecbf_idx',
            old_name='reporting_da_depot_i_2872a8_idx',
        ),
    ]
