# Generated by Django 4.2.30 on 2026-05-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytrack_compliance', '0003_serviceschedule'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inspectionlog',
            new_name='mytrack_com_vehicle_fe276e_idx',
            old_name='mytrack_com_vehicle_idx',
        ),
        migrations.AlterField(
            model_name='vehicledocument',
            name='label',
            field=models.CharField(blank=True, help_text='Optional custom label', max_length=100),
        ),
    ]
