# Generated by Django 5.1.15 on 2026-05-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytrack_compliance', '0004_rename_mytrack_com_vehicle_idx_mytrack_com_vehicle_fe276e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledocument',
            name='warning_days',
            field=models.PositiveIntegerField(default=30, help_text='Days before expiry to start showing a warning for this document'),
        ),
    ]
